--INSERT INTO tb_client (nm_name, nm_nick_name, dd_birthday, dt_created, nm_created) VALUES ('Fernandes Silva', 'choyo', '1979-05-02', CURRENT_TIME, 'admin');
--INSERT INTO tb_contact (nm_cellphone, nm_email, co_seq_client, dt_created, nm_created) VALUES ('+5511940748828', 'fernandesgs10@gmail.com', 1, CURRENT_TIME, 'admin');
--INSERT INTO tb_address (nm_address, nm_address_number, nm_address_city_code, nm_address_zip_code, co_seq_client, dt_created, nm_created) VALUES ('Nicolls Dr.', '7007', 'Bronx', '1248', 1, CURRENT_TIME, 'admin');
----
--INSERT INTO tb_client (nm_name, nm_nick_name, dd_birthday, dt_created, nm_created) VALUES ('Test', 'test', '1984-04-04', CURRENT_TIME, 'admin');
--INSERT INTO tb_client (nm_name, nm_nick_name, dd_birthday, dt_created, nm_created) VALUES ('Test2', 'test2', '1984-04-04', CURRENT_TIME, 'admin');
--INSERT INTO tb_contact (nm_cellphone, nm_email, co_seq_client, dt_created, nm_created) VALUES ('+5511940313247', 'test10@gmail.com', 2, CURRENT_TIME, 'admin');
--INSERT INTO tb_address (nm_address, nm_address_number, nm_address_city_code, nm_address_zip_code, co_seq_client, dt_created, nm_created) VALUES ('new york.', '7007', 'Bronx', '1248', 1, CURRENT_TIME, 'admin');
----
